# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Azure Blob Storage Upload
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          sas_token: "sp=racwdl&st=2023-09-07T18:20:02Z&se=2025-09-08T02:20:02Z&spr=https&sv=2022-11-02&sr=c&sig=${{secrets.SAS}}"
          account_name: asdfaefasfafasflkj
          container_name: "$web"
          source_dir: dist/azure-devops-variable-group-editor/
          sync: true
      - name: Azure service principal login ${{vars.TEST.clientId}}
        uses: azure/login@v1
        with:
          creds: ${{ vars.TEST }}
      - name: Purge Azure CDN
        uses: svanboxel/azure-purge-cdn@main
        with:
          cdn_endpoint: azuredevopshelpers
          cdn_profile_name: azuredevopshelpers
          resource_group: DevPlay
      - name: Azure service principal logout
        run: |
          az logout
