# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
        sas_token: 'sp=racwdl&st=2023-09-07T18:20:02Z&se=2025-09-08T02:20:02Z&spr=https&sv=2022-11-02&sr=c&sig=4I1UCIBb%2F%2F7nQeENDXGhDqtn1h4Ptdem66%2F1s6lpOS0%3D'
        account_name: asdfaefasfafasflkj
        container_name: '$web'
        source_dir: dist/azure-devops-variable-group-editor/
        sync: true

    - name: Azure service principal login
      uses: azure/login@v1.4.6
      with:
        creds: ${{ vars.SECC }}
        client-id: f21433a2-ab6e-46cc-ad0a-49380cb793bc
        tenant-id: 0b87cf55-9acf-46bc-bc21-c86bdad6175c
        subscription-id: 68a7f4e7-d274-4771-9bb8-4627ccc069c2
        
        
    - name: Purge Azure CDN
      uses: SvanBoxel/azure-purge-cdn@1.0.0
      with:
        # CDN endpoint
        cdn_endpoint: https://azuredevopshelpers.azureedge.net
        # Profile name of CDN
        cdn_profile_name: azuredevopshelpers
        # Resource Group Name
        resource_group: DevPlay

    - name: Azure service principal logout
      run: |
        az logout
